const fs = require('fs');
const path = require('path');
const root = __dirname;
const source = path.resolve(root, '../topmeds.co.uk');
const write = (file, text) => { fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true}); fs.writeFileSync(path.join(root,file),text); };
if (!fs.existsSync(path.join(root,'source/homepage-original.html'))) write('source/homepage-original.html',fs.readFileSync(path.join(root,'index.html'),'utf8'));
const rename = text => text.replace(/topmeds/g,'toppharma').replace(/Top Meds/g,'Top Pharma').replace(/TopMeds/g,'TopPharma').replace(/topmeds/g,'toppharma').replace(/>meds</g,'>pharma<').replace(/#243d70/g,'#174e46');
for (const file of ['tools/build.js','tools/finalize.js','tools/verify.js','assets/js/site.js','assets/css/site.css','404/error.php']) write(file,rename(fs.readFileSync(path.join(source,file),'utf8')));
let build = fs.readFileSync(path.join(root,'tools/build.js'),'utf8');
const start = build.indexOf("page('','Medicine information across the UK'");
const end = build.indexOf("page('shop'",start);
build = build.slice(0,start) + "page('','Medicine information & patient resources UK','Explore Top Pharma medicine guides, health topics and patient resources. Find information to help prepare for a conversation with your doctor or pharmacist.',require('./homepage')({link,catCards,medCards,meds,faq}),'');\n" + build.slice(end);
build = build.replace('Clear medicine information. More confident conversations.','Independent medicine information · For readers across the UK').replace('INFORMATION & WELLBEING','YOUR MEDICINE COMPANION').replace('Clear information for your next<br>conversation about health.','Make room for better questions.<br>Start with reliable information.').replace('Information, thoughtfully organised.','Knowledge for your next conversation.');
build = build.replace('A little more understanding.<br>One medicine at a time.','Your medicine.<br>A clearer starting point.').replace('Find a place to start.','Explore what matters to you.').replace('Clear information.<br>Thoughtfully organised.','A thoughtful companion<br>to your medicine questions.').replace('Find the right support.','Take your question to the right person.').replace('Understanding prescriptions.','Before your next prescription conversation.').replace('Practical delivery questions.','Ask your pharmacy about delivery.');
build = build.replace("['seizures','Anxiety & seizure disorders'","['seizures','Seizure-related medicines'");
build = build.replace("const schema = {'@context'", "const schema = {'@context'");
build = build.replace("write(file, local(html));", "write(file, local(html).replaceAll('â†—','↗').replaceAll('â†’','→').replaceAll('â˜°','☰').replaceAll('Â©','©').replaceAll('â€™','’')); ");
build = build.replace("require('./finalize');", "require('./finalize');\nrequire('./editorial');");
write('tools/build.js',build);
write('tools/finalize.js',fs.readFileSync(path.join(root,'tools/finalize.js'),'utf8').replace('topmeds','toppharma'));
let verify = fs.readFileSync(path.join(root,'tools/verify.js'),'utf8').replace('northwestmeds|','topmeds|northwestmeds|').replace("'medicine-price-list.txt'","'README.md'");
write('tools/verify.js',verify);
write('assets/css/site.css',fs.readFileSync(path.join(root,'assets/css/site.css'),'utf8').replaceAll('âˆ’','−')+'\n'+fs.readFileSync(path.join(root,'tools/theme.css'),'utf8'));
write('README.md',`# Top Pharma informational website\n\nPreview: http://localhost/toppharma.co.uk/\n\nBuild: node tools/build.js\nVerify: node tools/verify.js\n\nThe homepage follows the supplied document section order, adapted to an informational service. The original is preserved in source/homepage-original.html and blocked from HTTP access. No ordering, payment, prescription upload or spreadsheet integration is enabled.\n\nGSC, GA4 and body integrations remain pending. Add supplied tags to the shared page template in tools/build.js, update the privacy policy if data collection changes, then rebuild. No identifiers or endpoints are reused from another site.\n\nDeploy the generated directories, assets, index.html, robots.txt, sitemap.xml and .htaccess to the toppharma.co.uk document root on Apache with mod_rewrite and PHP enabled (PHP renders the real 404 response). Keep tools, source, setup.js and README.md private. Canonicals use HTTPS without www and directory URLs. Test HTTPS and host redirects on the production server before launch; local tests cannot validate hosting or Search Console indexing.\n\nContent sources: linked NHS medicine resources and electronic Medicines Compendium, checked 5 September 2026. These are navigation guides, not clinical reviews. Website contact details have not been supplied.\n`);
console.log('Prepared Top Pharma source and assets.');
