const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const origin = 'https://toppharma.co.uk';
const write = (name, value) => { const target = path.join(root, name); fs.mkdirSync(path.dirname(target), {recursive:true}); fs.writeFileSync(target, value); };
if (!fs.existsSync(path.join(root, 'source/homepage-original.html'))) {
  write('source/homepage-original.html', fs.readFileSync(path.join(root, 'index.html'), 'utf8'));
}
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories = [
 ['anxiety','Anxiety & panic disorders','Understanding anxiety, preparing for an appointment and finding reliable medicine information.','01'],
 ['sleep','Sleep & insomnia','Explore information about sleep difficulties and medicines discussed with a prescriber.','02'],
 ['nerve-pain','Nerve pain & neuropathy','A starting point for conversations about nerve pain and your treatment plan.','03'],
 ['wakefulness','ADHD & wakefulness','Find condition resources. ADHD and excessive daytime sleepiness require separate clinical assessment.','04'],
 ['seizures','Seizure-related medicines','Resources to help you understand medicines and prepare questions for your care team.','05'],
 ['sedation','Short-term sedation','Information to discuss with the clinical team responsible for a planned procedure.','06'],
 ['pain','Moderate to severe pain','Find guidance on discussing pain and treatment options with a healthcare professional.','07']
];
const meds = [
 ['diazepam','Diazepam',['anxiety','seizures'],'https://www.nhs.uk/medicines/diazepam/','NHS medicine guide'],
 ['lorazepam','Lorazepam',['anxiety','sleep'],'https://www.nhs.uk/medicines/lorazepam/','NHS medicine guide'],
 ['clonazepam','Clonazepam',['seizures'],'https://www.nhs.uk/medicines/clonazepam/','NHS medicine guide'],
 ['zopiclone','Zopiclone',['sleep'],'https://www.nhs.uk/medicines/zopiclone/','NHS medicine guide'],
 ['pregabalin','Pregabalin',['nerve-pain','anxiety','seizures'],'https://www.nhs.uk/medicines/pregabalin/','NHS medicine guide'],
 ['alprazolam','Alprazolam',['anxiety'],'https://www.medicines.org.uk/emc/','Search the electronic Medicines Compendium'],
 ['nitrazepam','Nitrazepam',['sleep'],'https://www.medicines.org.uk/emc/','Search the electronic Medicines Compendium'],
 ['midazolam','Midazolam',['sedation'],'https://www.medicines.org.uk/emc/','Search the electronic Medicines Compendium'],
 ['modafinil','Modafinil',['wakefulness'],'https://www.medicines.org.uk/emc/','Search the electronic Medicines Compendium'],
 ['bromazepam','Bromazepam',['anxiety'],'https://www.medicines.org.uk/emc/','Search the electronic Medicines Compendium']
];
const pages = [];
const link = (href, label, cls='') => `<a href="${href}"${cls ? ` class="${cls}"`:''}>${label}</a>`;
function page(route, title, description, body, active='', noindex=false) {
 const file = route ? `${route}/index.html` : 'index.html';
 const prefix = route ? '../'.repeat(route.split('/').length) : './';
 const url = `${origin}/${route ? route+'/' : ''}`;
 const local = s => s.replace(/href="\/(?!\/)/g,`href="${prefix}`);
 const nav = [['','Home'],['shop','Medicines'],['category','Categories'],['about-us','About'],['contact-us','Contact']].map(([r,l]) => `<a href="/${r ? r+'/' : ''}"${active===r?' aria-current="page"':''}>${l}</a>`).join('');
 const schema = {'@context':'https://schema.org','@type':'WebPage',name:title,description,url,isPartOf:{'@type':'WebSite',name:'Top Pharma',url:origin+'/'}};
 const html = `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | Top Pharma</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><link rel="canonical" href="${url}"><meta name="theme-color" content="#174e46"><meta property="og:type" content="website"><meta property="og:site_name" content="Top Pharma"><meta property="og:title" content="${esc(title)} | Top Pharma"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:locale" content="en_GB"><meta name="twitter:card" content="summary"><link rel="icon" href="${prefix}assets/img/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}assets/css/site.css"><script defer src="${prefix}assets/js/site.js"></script><script type="application/ld+json">${JSON.stringify(schema)}</script><!-- TopPharma head tags: awaiting supplied GSC / GA4 configuration. --></head><body><!-- TopPharma body tags: awaiting supplied configuration. --><a class="skip" href="#main">Skip to content</a><div class="topbar">Independent medicine information · For readers across the UK</div><header class="header"><div class="wrap navrow"><a class="logo" href="/" aria-label="Top Pharma home"><span class="mark" aria-hidden="true">+</span><span>top<span class="logolight">pharma</span><small>YOUR MEDICINE COMPANION</small></span></a><button class="menu" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation">${nav}</nav><a class="navcta" href="/shop/">Explore medicines <span aria-hidden="true">↗</span></a></div></header><main id="main">${local(body)}</main><footer><div class="wrap footergrid"><div><a class="logo" href="/"><span class="mark" aria-hidden="true">+</span><span>top<span class="logolight">pharma</span></span></a><p>Make room for better questions.<br>Start with reliable information.</p><span class="pill">An independent information resource</span></div><div><h2>Explore</h2>${link('/shop/','Medicine directory')}${link('/category/','Health categories')}${link('/prescription-information/','Prescription information')}</div><div><h2>Useful information</h2>${link('/about-us/','About Top Pharma')}${link('/delivery-information/','Delivery information')}${link('/contact-us/','Contact & support')}</div><div><h2>About this website</h2>${link('/privacy-policy/','Privacy policy')}${link('/terms-and-conditions/','Terms of use')}<p>General information only.<br>For personal advice, speak to your doctor or pharmacist.</p></div></div><div class="wrap footerbase"><span>© ${new Date().getFullYear()} Top Pharma</span><span>Knowledge for your next conversation.</span></div></footer></body></html>`;
 write(file, local(html).replaceAll('â†—','↗').replaceAll('â†’','→').replaceAll('â˜°','☰').replaceAll('Â©','©').replaceAll('â€™','’'));  if (!noindex) pages.push({file,url});
}
const intro = (eyebrow,title,text) => `<section class="pageintro"><div class="wrap"><div class="crumb">${link('/','Home')} <span>/</span> ${esc(eyebrow)}</div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${text}</p></div></section>`;
const catCards = () => categories.map(([slug,name,desc,num]) => `<a class="categorycard" href="/category/${slug}/"><span class="categorynum">${num}</span><h3>${name}</h3><p>${desc}</p><span class="arrow" aria-hidden="true">↗</span></a>`).join('');
const medCards = list => list.map(([slug,name,cats])=>`<article class="medicinecard" data-search="${esc(name.toLowerCase()+' '+cats.map(c=>categories.find(x=>x[0]===c)[1].toLowerCase()).join(' '))}" data-categories="${cats.join(' ')}"><div class="medart" aria-hidden="true"><span class="abstractpill"></span><span class="monogram">${name.slice(0,2)}</span></div><div class="cardbody"><span class="eyebrow">Medicine information</span><h3>${link('/shop/medicine/'+slug+'/',name)}</h3><p>Patient resources & questions for your pharmacist.</p>${link('/shop/medicine/'+slug+'/','Read information <span aria-hidden="true">→</span>','textlink')}</div></article>`).join('');
const faq = [
 ['Is Top Pharma available throughout the UK?','The information on this website can be read across England, Scotland, Wales and Northern Ireland. This website does not dispense or deliver medicines.'],
 ['Do I need a prescription to order medicines?','Top Pharma does not accept medicine orders. Discuss prescription requirements and medicine suitability with a qualified healthcare professional.'],
 ['How do I find a medicine on Top Pharma?','Use the medicine directory search or browse by category. Each medicine page links to an external patient information resource.'],
 ['Can I contact someone about my medicine?','Speak to your doctor or pharmacist for personalised advice. The contact page explains where to find appropriate support.'],
 ['How will my medicine be delivered?','Top Pharma does not arrange delivery. If another pharmacy dispenses your medicine, contact that pharmacy about its delivery arrangements.']
];
page('','Medicine information & patient resources UK','Explore Top Pharma medicine guides, health topics and patient resources. Find information to help prepare for a conversation with your doctor or pharmacist.',require('./homepage')({link,catCards,medCards,meds,faq}),'');
page('shop','Medicine directory','Search the Top Pharma medicine information directory by medicine name or health category. Find patient resources and questions to discuss with your pharmacist.',intro('Medicine directory','Your medicine.<br>A clearer starting point.','Browse medicine guides and linked patient resources. These pages provide information, not a recommendation for treatment.')+`<section class="section wrap"><form class="filters" role="search"><div><label for="medicine-search">Search medicines</label><input id="medicine-search" type="search" placeholder="Try diazepam or sleep" autocomplete="off"></div><div><label for="category-filter">Health category</label><select id="category-filter"><option value="">All categories</option>${categories.map(([s,n])=>`<option value="${s}">${n}</option>`).join('')}</select></div><button type="reset" class="button secondary">Reset filters</button></form><p id="result-count" role="status" aria-live="polite">${meds.length} medicine guides</p><div class="medicinegrid">${medCards(meds)}</div><p id="empty-state" hidden>No medicine guides match your search. Try another name or reset the filters.</p><noscript><p>All guides are listed below. Enable JavaScript to filter them.</p></noscript></section>`,'shop');
page('category','Health categories','Browse seven Top Pharma health information categories, from anxiety and sleep to nerve pain and prescription medicine resources.',intro('Health categories','Explore what matters to you.','Browse by health topic to find related medicine resources. Categories organise information and do not establish that a medicine is suitable for you.')+`<section class="section wrap"><div class="categorygrid">${catCards()}</div></section>`,'category');
categories.forEach(([slug,name,desc])=>{
 const related=meds.filter(m=>m[2].includes(slug));
 page('category/'+slug,name+' information',desc+' Explore related Top Pharma information pages.',intro(name,name,desc)+`<section class="section wrap"><div class="reading"><h2>Prepare for a useful conversation</h2><p>Make a note of your symptoms, how they affect your daily life and what you would like to understand. Take a list of your current medicines to your appointment.</p><p>Ask your healthcare professional which options are appropriate for your circumstances, what follow-up you need and where to find reliable patient information.</p>${slug==='wakefulness'?'<p>ADHD and problems with wakefulness are distinct topics. A listing here does not mean a medicine is approved or appropriate for ADHD.</p>':''}<p>${link('https://www.nhs.uk/conditions/','Explore the NHS conditions directory ↗','textlink')}</p></div><h2>Related medicine resources</h2>${related.length?`<div class="medicinegrid">${medCards(related)}</div>`:'<p>There are no dedicated medicine guides in this category yet. Start with the NHS conditions directory or speak to your pharmacist.</p>'}</section>`,'category');
});
meds.forEach(([slug,name,cats,url,label])=>page('shop/medicine/'+slug,name+' information',`Find ${name} patient resources, a checklist of questions for your pharmacist and guidance on locating the leaflet for your exact medicine.`,intro('Medicine guide',name,'Patient information resources and questions to discuss with your healthcare professional.')+`<section class="section wrap articlelayout"><article class="reading"><span class="pill">Information guide</span><h2>Understanding your ${name.toLowerCase()} information</h2><p>Start with the patient information leaflet for the exact medicine you have been prescribed. Check the name, formulation and strength on your packaging against the leaflet.</p><p>This page is a navigation guide. It does not confirm the availability, licensing status or suitability of a particular brand or preparation.</p><h2>Read the patient resource</h2><p>${label.startsWith('NHS')?`The NHS provides a guide to ${name.toLowerCase()} with sections covering medicine use and patient questions.`:`Use the electronic Medicines Compendium to look for the exact medicine or product name. If you cannot find a matching leaflet, ask your pharmacist; do not assume that another product's leaflet applies.`}</p>${link(url,label+' ↗','button')}<h2>Questions for your pharmacist</h2><ul><li>What has this medicine been prescribed for in my treatment plan?</li><li>Where can I find the leaflet for my exact preparation?</li><li>What should I know about side effects and interactions?</li><li>What should I do if I miss a dose or have concerns?</li><li>When should I have a follow-up review?</li></ul><h2>Your treatment is personal</h2><p>Ask your prescriber or pharmacist before making changes to your treatment. This website cannot provide an individual assessment or a dosing plan.</p><div class="sourcebox"><h2>Reference</h2><p>${link(url,label)}. Resource linked on 5 September 2026. No clinical review of this page is claimed.</p></div></article><aside class="sidepanel"><span class="eyebrow">EXPLORE FURTHER</span><h2>Related topics</h2>${cats.map(c=>link('/category/'+c+'/',categories.find(x=>x[0]===c)[1]+' →')).join('')}<hr><h3>Have a medicine question?</h3><p>Your doctor or pharmacist can advise on your circumstances.</p>${link('/contact-us/','Find the right support →','textlink')}</aside></section>`,'shop'));
const article = (title, content)=>intro('Useful information',title,'Practical information from Top Pharma.')+`<section class="section wrap"><article class="reading">${content}</article></section>`;
page('about-us','About Top Pharma','Learn about Top Pharma, an independent medicine information website that organises patient resources and questions for healthcare conversations.',article('A thoughtful companion<br>to your medicine questions.',`<h2>About Top Pharma</h2><p>Top Pharma is an independent information website for people who want a clearer starting point for medicine questions. Browse by name or topic, then use the linked patient resources to explore further.</p><h2>What this website provides</h2><p>A medicine directory, topic pages and practical information about preparing for conversations with a doctor or pharmacist.</p><h2>Our editorial approach</h2><p>Medicine pages link to NHS resources where available and to the electronic Medicines Compendium for product leaflet searches. Our pages do not replace those resources or professional advice.</p><h2>Service scope</h2><p>This website does not dispense medicines, assess prescriptions or provide personalised medical advice. It does not claim pharmacy registration or clinical accreditation.</p>`),'about-us');
page('contact-us','Contact and support','Find the right place for medicine questions, personal healthcare advice and practical support. Top Pharma does not collect medical enquiries.',article('Take your question to the right person.',`<h2>Questions about your medicine</h2><p>Contact the doctor who prescribed your medicine or the pharmacist who dispensed it. They can consider your treatment history and the exact product you have.</p><h2>Help finding NHS services</h2><p>${link('https://www.nhs.uk/nhs-services/','Browse NHS services ↗','button')}</p><h2>Urgent help</h2><p>Use the official NHS website for information about urgent and emergency care in your area.</p><p>${link('https://www.nhs.uk/nhs-services/urgent-and-emergency-care-services/','NHS urgent and emergency care information ↗','textlink')}</p><h2>Website enquiries</h2><p>A website contact address has not yet been published. This website has no enquiry form and does not collect prescriptions or health information.</p>`),'contact-us');
page('prescription-information','Prescription information','Prepare questions about prescriptions, medicine leaflets and follow-up care before speaking with your doctor or pharmacist.',article('Before your next prescription conversation.',`<h2>Start with your healthcare professional</h2><p>Discuss whether a medicine is appropriate for you and what prescription requirements apply. Top Pharma does not assess prescriptions or supply medicines.</p><h2>Before your appointment</h2><ul><li>Bring a list of your current medicines and supplements.</li><li>Make a note of questions about your treatment.</li><li>Ask how to get further help or arrange a review.</li></ul><h2>Find official guidance</h2><p>${link('https://www.nhs.uk/nhs-services/prescriptions/','NHS prescription information ↗','button')}</p>`));
page('delivery-information','Medicine delivery information','Questions to ask your dispensing pharmacy about medicine delivery, dispatch, storage instructions and missed deliveries.',article('Ask your pharmacy about delivery.',`<h2>Speak to your dispensing pharmacy</h2><p>Top Pharma does not dispatch medicines or arrange delivery. Contact the pharmacy handling your prescription for information specific to your order.</p><h2>Useful things to check</h2><ul><li>When should you expect dispatch and delivery?</li><li>Does someone need to be available to receive the parcel?</li><li>Are there any special storage or handling instructions?</li><li>Who should you contact about a delay or damaged packaging?</li></ul><p>Follow the advice supplied with your medicine and ask your pharmacist if anything is unclear.</p>`));
page('privacy-policy','Privacy policy','How this Top Pharma informational website handles browsing, cookies, external links and data collection.',article('Privacy policy.',`<p>Last updated: 5 September 2026.</p><h2>Browsing this website</h2><p>This version of Top Pharma has no accounts, contact forms, advertising trackers or analytics integrations. The site code does not store search entries, set cookies or use browser storage.</p><h2>Server logs</h2><p>The hosting server may record standard request information, such as IP addresses and requested URLs. Retention and access depend on the hosting configuration.</p><h2>External resources</h2><p>Following a link to another website takes you to that provider's service, where its own privacy policy applies.</p><h2>Future changes</h2><p>This policy must be updated before enabling services that collect personal information. A privacy contact has not yet been published.</p>`));
page('terms-and-conditions','Terms of use','Read the terms for using Top Pharma medicine information, including the limits of general resources and external references.',article('Terms of use.',`<h2>General information</h2><p>Top Pharma provides general information and links to patient resources. It is not a healthcare consultation, diagnosis or treatment recommendation.</p><h2>Professional advice</h2><p>Your doctor or pharmacist can advise on your personal circumstances. Do not rely on this website for a dosing plan or changes to prescribed treatment.</p><h2>External links</h2><p>External websites are independently maintained. Refer to the current resource and check that any product leaflet matches your medicine.</p><h2>No sales service</h2><p>This website does not accept medicine orders, payments or prescriptions.</p>`));
page('404','Page not found','The requested Top Pharma page could not be found.',intro('Page not found','Let’s get you back on track.','The page you requested is not available.')+`<section class="section wrap">${link('/','Return home','button')} ${link('/shop/','Browse medicine guides','button secondary')}</section>`,'',true);
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`\n<url><loc>${p.url}</loc></url>`).join('')}\n</urlset>\n`);
write('robots.txt',`User-agent: *\nAllow: /\nDisallow: /source/\nDisallow: /tools/\nDisallow: /medicine-price-list.txt\nSitemap: ${origin}/sitemap.xml\n`);
write('.htaccess',`Options -Indexes -MultiViews\nDirectoryIndex index.html\nRewriteEngine On\n# Local previews use the subdirectory prefix; production uses the domain root.\nRewriteBase /\nRewriteRule ^(?:source|tools)(?:/|$) - [F,L]\nRewriteRule ^medicine-price-list\\.txt$ - [F,L,NC]\nRewriteCond %{HTTP_HOST} ^(?:www\\.)?toppharma\\.co\\.uk$ [NC]\nRewriteCond %{HTTPS} !=on [OR]\nRewriteCond %{HTTP_HOST} ^www\\. [NC]\nRewriteRule ^ https://toppharma.co.uk%{REQUEST_URI} [R=301,L,NE]\nRewriteCond %{THE_REQUEST} \\s/+(.*/)?index\\.html(?:[?\\s]) [NC]\nRewriteRule ^(.*/)?index\\.html$ /$1 [R=301,L]\n# Set an ErrorDocument appropriate to local previews or production.\n<If "%{HTTP_HOST} == 'localhost'">\nErrorDocument 404 /toppharma.co.uk/404/\n</If>\n<Else>\nErrorDocument 404 /404/\n</Else>\n`);
write('assets/img/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="18" fill="#174e46"/><path d="M27 14h10v13h13v10H37v13H27V37H14V27h13z" fill="#fff"/></svg>');
write('tools/pages.json',JSON.stringify(pages,null,2));
console.log(`Built ${pages.length} indexable pages and a 404 page.`);
require('./finalize');
require('./editorial');
require('./brand-assets');
